### ISSUE TITLE
Is Electron supported?

### ISSUE THREAD

**Issue by sogoogos** [DominicTobias/react-image-crop#414] opened 2021-04-10 01:36 UTC
I am trying to use this library in my Electron app. 
However, simply using
```
function CropDemo({ src }) {
  const [crop, setCrop] = useState({ aspect: 16 / 9 });
  return <ReactCrop src={src} crop={crop} onChange={newCrop => setCrop(newCrop)} />;
}
```
did not work in [Electron](https://www.electronjs.org/). As seen below, only an orange frame was displayed around the image and I was not able to crop it. 

https://user-images.githubusercontent.com/24484961/114254006-f7463280-99e7-11eb-8dbf-cd08b1032be6.mov

**Comment by DominicTobias** [comment] 2021-04-12 14:50
Hi I've never tried it on electron though I'm not sure why it wouldn't. Have you included the CSS?

**Comment by sogoogos** [comment] 2021-04-14 21:32
> Hi I've never tried it on electron though I'm not sure why it wouldn't. Have you included the CSS?

@DominicTobias Yes, I included `import 'react-image-crop/dist/ReactCrop.css';` but the result was the samel.

**Comment by vitorizkiimanda** [comment] 2021-04-26 06:16
@sogoogos @DominicTobias i tried to implement to electron based app and the result is same. unable to crop, no cropper UI appears on top of the image. however, there are no error message in console

**Comment by virinchi-manepalli-trysolvio** [comment] 2021-06-01 10:43
@sogoogos @DominicTobias I resolved this issue.  react image cropper supports electron. the issue is from web packs.
CSS-loader and style-loader should be in dev dependencies. 
just do **yarn remove css-loader** and style-loader and do ### yarn add -D css-loader
make sure to add css-loader in webpack as well in this manner

```
 module: {
    rules: [
      {
        test: /\.(js|ts|tsx)$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
        },
      },
      {
        test: /\.css$/i,
        use: ['style-loader', 'css-loader'],
      },
    ],
  },
```

**Comment by vitorizkiimanda** [comment] 2021-06-01 10:50
welp~ thats nice info, let me try it

**Comment by sogoogos** [comment] 2021-06-05 04:36
@virinchi-manepalli-trysolvio Thanks! It worked!

**Comment by DominicTobias** [comment] 2021-06-14 15:22
Thanks for finding a fix @virinchi-manepalli-trysolvio , since the issue was related to loading the CSS correctly going to close this

**Closed by DominicTobias** 2021-06-14 15:22 UTC
