### ISSUE TITLE
Crop aspect issue

### ISSUE THREAD

**Issue by wesleywong** [DominicTobias/react-image-crop#252] opened 2019-04-09 01:56 UTC
I had an issue when cropping some image that doesn't need an aspect ratio. If the config without 'aspect' that it won't be calling onChange callback in the initial load. Mean that the cropping action only performs when you click on the marquee area. 

example:
`state = {
    src: null,
    crop: {
      x: 20,
      y: 10,
      width: 30,
      height: 30
    }
  };`

[https://codesandbox.io/s/k58lz4y2v7](url)

is there a way to trigger onChange and onComplete in the initial load the same as when I provide aspect.

**Comment by DominicTobias** [comment] 2019-04-09 19:13
Hi,

This is as intended - onChange and onComplete is only initially called if the library changed or completed the crop when an aspect was passed in. Since your crop wasn't changed on the first load no change is fired. If you want to perform some logic when after the initial load you can do it in `onImageLoaded`. What are you trying to achieve?

**Comment by DominicTobias** [comment] 2019-06-11 17:04
This fires onChange/onComplete in v7 and v8, closing

**Closed by DominicTobias** 2019-06-11 17:04 UTC
