### ISSUE TITLE
Toggle of aspect-ratio is broken

### ISSUE THREAD

**Issue by TimSusa** [DominicTobias/react-image-crop#133] opened 2017-10-27 10:01 UTC
When changing the crop.aspect prop, the component does not immediately represent the new cropping state. Only after manually changing the crop with the mouse, it changes.  

This was working in Version: 2.0.8
This is broken in Version: 3.0.2

**Comment by DominicTobias** [comment] 2017-10-27 15:48
Hi,

I can't replicate you're issue. Can you post some code you're trying? See the https://github.com/DominicTobias/react-image-crop/blob/master/demo/demo.js for some example usage. I suspect you haven't adjusted your code for v3, which unfortunately makes using an aspect with a width + height a bit less convenient out of necessity. Check the release notes and the demo code.

Working:

![aspect-working](https://user-images.githubusercontent.com/760314/32112966-b2789424-bb36-11e7-87fb-5438323f71bb.gif)

**Comment by TimSusa** [comment] 2017-11-06 14:48
We observed two effects:

1: Changing the cropping to overlap the image, does not clamp the cropping area. Only after moving the cropping area, it is clamped to image boundaries.

2: Toggling the aspect ratio will not trigger onUpdate

Please see the demo code below and the gif we provided.

![cropping-bug](https://user-images.githubusercontent.com/8963529/32446621-cbc710ba-c309-11e7-8196-9b8c3f480993.gif)

```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import ReactCrop, { makeAspectCrop } from 'react-image-crop'
import 'react-image-crop/dist/ReactCrop.css'

class App extends Component {
  state = {
    crop: {
      aspect: 16 / 9
    },
    height: 0,
    width: 0
  }

  onChange = (crop, pixelCrop) => {
    console.log(crop, pixelCrop)
    this.setState({ crop })
  }

  buttonClick = () => {
    this.setState({
      crop: makeAspectCrop({ ...this.state.crop, aspect: this.state.crop.aspect > 1 ? 9 / 16 : 16 / 9 }, this.state.width / this.state.height)
    })
  }

  onImageLoaded = (image) => {
    this.setState({
      crop: makeAspectCrop(this.state.crop, image.width / image.height),
      height: image.height,
      width: image.width
    });
  }

  render() {
    const { crop } = this.state

    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <ReactCrop
          src='URL'
          crop={crop}
          onChange={this.onChange}
          onImageLoaded={this.onImageLoaded}
        />
        <button onClick={this.buttonClick}>
          toggle
        </button>
      </div>
    );
  }
}

export default App;
```

**Comment by DominicTobias** [comment] 2017-11-07 15:10
Thanks I'll have to check it out, though I'm on vacation for a week tomorrow so may have to wait until after

**Comment by bakerGS** [comment] 2018-11-13 20:53
Hi,

Did you find a solution for this problem?

I am facing with the same issue you described.

Thanks!

**Comment by DominicTobias** [comment] 2018-11-13 21:49
I was about to say I couldn't replicate but I've only just realised what the issue is - it's when you change only the aspect, otherwise it works. I will fix this in the next few days.

**Comment by DominicTobias** [comment] 2018-11-13 22:37
Fixed in 6.0.6

**Closed by DominicTobias** 2018-11-13 22:37 UTC

**Comment by bakerGS** [comment] 2018-11-14 10:53
Thanks,

But I think is still with problems.

You can check on your sandbox (https://codesandbox.io/s/72py4jlll6) and changing aspectRatio to 2/3 for example.

Look at this example:

![react-image-crop](https://user-images.githubusercontent.com/255518/48478154-bf7d3580-e803-11e8-822d-3917a24e56eb.gif)

At the example above you can see after changing the image, the aspect ratio is not 2/3, is like a square.

Can I reset the crop dimensions in some way to fix it?

Thanks again for your time!

**Comment by DominicTobias** [comment] 2018-11-14 10:57
@bakerGS did you upgrade the sandbox version of react-image-crop to 6.0.7? My sandbox is currently on the unfixed version so just making sure

**Comment by bakerGS** [comment] 2018-11-14 11:09
You're right, thanks for your help!!!

**Comment by DominicTobias** [comment] 2018-11-14 16:36
@bakerGS unfortunately due to this introducing a bug I had to revert this, so just like when you initially set a crop you must omit (or set to falsy) either width or height when changing the aspect in order for the component to generate a new complete crop:

```js
this.setState(state => ({
  crop: {
    ...state.crop,
    aspect: 16/9,
    width: null,
  },
}))
```

**Comment by bakerGS** [comment] 2018-11-15 12:48
@DominicTobias Can you tell me the new bug? I can't find it.

**Comment by DominicTobias** [comment] 2018-11-15 12:57
I’ve fixed the bug now, the change I made for this was causing an infinite
loop. If you want to change the aspect and let the component figure out the
adjustment in width or height then set width or height to null at the same
time
