### ISSUE TITLE
Setting aspect and just one of width or height won't show crop selection

### ISSUE THREAD

**Issue by echojc** [DominicTobias/react-image-crop#36] opened 2016-05-26 06:00 UTC
Hi, I'm not sure if this is by design, but the following example in the readme:

```js
var crop = {
    width: 30,
    aspect: 16/9
}
```

won't display the crop selection because `height` is falsy, which sets `this.cropInvalid` to true.

However, later on in `ensureAspectDimensions`, since `width` and `aspect` are both set, the value for `height` becomes fixed to something valid anyway, and the same if only `height` and `aspect` are set. Because of this, do you think the crop selection should be rechecked for validity after `ensureAspectDimensions`?

Thanks for your time!

**Comment by DominicTobias** [comment] 2016-05-27 14:02
Hi, that's interesting - good point it should not be invalid - just to be clear is it affecting the crop (like not being drawn out?) If so might be a regression

**Comment by echojc** [comment] 2016-05-29 04:18
Yeah, the crop selection isn't being drawn out if you just set `width` and `aspect`.

**Comment by DominicTobias** [comment] 2016-05-29 09:43
Actually I can't reproduce this - the initial render happens with invalid params, but then once the image has loaded `ensureAspectDimensions` should get called and the crop becomes valid

<img width="551" alt="screen shot 2016-05-29 at 10 42 37" src="https://cloud.githubusercontent.com/assets/760314/15632469/342dcf28-258a-11e6-8bc2-0468882bda22.png">

**Comment by echojc** [comment] 2016-05-29 09:56
Ah, I think I'm setting the crop from the `onImageLoaded` callback because I need the natural image dimensions to calculate the corresponding percentage values for specific width/height sizes.

I'm not sure if that is why I'm not getting the crop; I'll try to find and post a minimum repro tomorrow. Thanks for looking into it!

**Comment by DominicTobias** [comment] 2016-05-29 10:01
Np, ah ok - that is supposed to still work but I'm able to reproduce the issue now so will take a look why it isn't

**Comment by DominicTobias** [comment] 2016-05-29 10:11
This should be fixed now please try `1.0.0-rc3`, closing but let me know if there are any probs

**Closed by DominicTobias** 2016-05-29 10:11 UTC

**Comment by echojc** [comment] 2016-05-29 23:49
I've confirmed it works, thanks for your work!
