### ISSUE TITLE
onCropComplete pixelCrop returns object with `0` values.

### ISSUE THREAD

**Issue by inferusvv** [DominicTobias/react-image-crop#91] opened 2017-03-21 10:18 UTC
I set image url and show ReactCrop component. If user don't change anything and confirm, `this.crop` will have 0 values, so backend will receive this wrong values.

  ```
onImageLoaded = (crop, img, pixelCrop) => {
    console.log('onImageLoaded', pixelCrop); // returns Object {x: 0, y: 0, width: 0, height: 0}
    this.crop = pixelCrop;
}

            <ReactCrop
              src={this.props.user.avatarForCrop}
              crop={this.state.crop}
              onImageLoaded={this.onImageLoaded}
              onComplete={this.onCropComplete}
              minWidth={this.state.crop.width}
              keepSelection
            />
```

**Comment by DominicTobias** [comment] 2017-03-21 16:10
Just to be clear - are you setting a crop on load or not? If not then this is correct

**Comment by inferusvv** [comment] 2017-03-21 17:24
No. If I have `this.props.user.avatarForCrop`, then I render `ReactCrop` component.

**Comment by DominicTobias** [comment] 2017-09-20 18:10
I'm closing this because it's old but let me know if you're still having issues. Will need a reproducible example because I can't replicate this.

**Closed by DominicTobias** 2017-09-20 18:10 UTC
