### ISSUE TITLE
Getting black image after crop.

### ISSUE THREAD

**Issue by WaqqarSuleman** [DominicTobias/react-image-crop#406] opened 2021-02-23 08:51 UTC
Hi,

I am getting **"solid black"** image after passing it through the `getCroppedImg()` function provided by the docs. The dimesions of the returned image is correct, however all I see is solid black color.

```
const reader = new FileReader();
const imageObject = new Image();
reader.readAsDataURL(fileObject);
reader.onload = () => {
	imageObject.src = reader.result;
};
const croppedImageBlob = await getCroppedImg(imageObject, crop, fileObject.name);
 console.log(URL.createObjectURL(croppedImageBlob));   //Pasting the URL in the browser shows a solid black image
```

Any help is appreciated.
Thanks.

**Comment by DominicTobias-b1** [comment] 2021-02-23 08:53
Hi, are you saving it as a jpg? You need to save as png to keep transparency

**Comment by WaqqarSuleman** [comment] 2021-02-23 08:54
> Hi, are you saving it as a jpg? You need to save as png to keep transparency

Oh, thanks. Let me try this out.

**Comment by WaqqarSuleman** [comment] 2021-02-23 08:58
@DominicTobias-b1 I changed the `getCroppedImg()` to the following:

```
export const getCroppedImg = (image, crop, fileName) => {
	const canvas = document.createElement('canvas');
	const scaleX = image.naturalWidth / image.width;
	const scaleY = image.naturalHeight / image.height;
	canvas.width = crop.width;
	canvas.height = crop.height;
	const ctx = canvas.getContext('2d');

	ctx.drawImage(
		image,
		crop.x * scaleX,
		crop.y * scaleY,
		crop.width * scaleX,
		crop.height * scaleY,
		0,
		0,
		crop.width,
		crop.height
	);

	return new Promise((resolve, reject) => {
		canvas.toBlob(
			blob => {
				blob.name = fileName;
				resolve(blob);
			},
			'image/png',    // changed to png
			1
		);
	});
};
```

Now, I am getting a solid white image. Am I doing something wrong?

**Comment by WaqqarSuleman** [comment] 2021-02-23 11:34
> > Hi, are you saving it as a jpg? You need to save as png to keep transparency
> 
> Oh, thanks. Let me try this out.

Getting naturalWidth and naturalHeight as 0, any idea why?

**Comment by norflin321** [comment] 2021-07-26 15:58
Final react component code with the problem solved: https://gist.github.com/norflin321/c8ce39f3fff2e73b7bc30b216b482a85

**Comment by DominicTobias** [comment] 2022-04-10 11:25
Thanks for the gist, closing as the issue is old and from a major version ago

**Closed by DominicTobias** 2022-04-10 11:25 UTC

**Comment by DominicTobias** [comment] 2023-05-11 20:39
> > Final react component code with the problem solved: https://gist.github.com/norflin321/c8ce39f3fff2e73b7bc30b216b482a85
> 
> 404. Please open issue

What version are you using and can you replicate the issue on [Codesandbox](https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-y831o)?

**Comment by ochekayjay** [comment] 2023-05-19 17:24
> Final react component code with the problem solved: https://gist.github.com/norflin321/c8ce39f3fff2e73b7bc30b216b482a85

Please I can't access this link, @DominicTobias @norflin321 @DinarSharipov @WaqqarSuleman can any of you please link me to the solution? I'm facing similar problem

**Comment by YosriBed** [comment] 2024-03-20 07:55
Facing the same issue

**Comment by m-nathani** [comment] 2024-11-05 04:02
Facing the same problem too.. though it was working earlier..
