### ISSUE TITLE
Crop overlay does not work in IE (Edge) nor FF.

### ISSUE THREAD

**Issue by projecteon** [DominicTobias/react-image-crop#34] opened 2016-05-02 13:27 UTC
Seems to be an issue with the use of clip-path: url(#clipping);
Might be missing svg elements to make this visible.

**Comment by DominicTobias** [comment] 2016-05-02 13:34
Hi what version of the component are you using? (It was supposed to have been fixed for FF). I need to check if Edge has compatibility with the css properties used, perhaps it can be fixed with `-ms-` prefix but only if it existed in E11 already. The alternative to not using CSS is ugly and less performant (moving 4 boxes around) so I opted for this as usually on admin systems you can enforce browser requirements.

**Comment by projecteon** [comment] 2016-05-02 13:59
Some small test code. Removing the svg tags around image makes the clip path fail in Edge. I haven't tried IE11. Our application needs to run on all major browers.

For our use I had to do some modifications to the current used code (might have to do more, not sure atm). Hence no example using the react component directly.

`<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <style>
        .container {
            background: #000;
        }

        .container > img.opace {opacity: 0.2}

        .container > img, .container > svg, img.clipped{
            position: absolute;
            top:0;
            left: 0;
        }

        svg > img, img.clipped {
            clip-path: url(#clipping);
        }

    </style>
</head>
<body style="overflow:auto; margin-left: 5px;">
    <svg>
        <defs>
            <clipPath id="clipping">
            <rect x="100" y="100" width="100" height="100" />
            </clipPath>
        </defs>
    </svg>

    <form>
    <div id="container" class="container">
        <image class='opace' src="humayun-thom-arno.jpg" width="500" height="350" style='z-index: -2'></image>
        <svg style='z-index: 2' width="500" height="350">
        <image class='clipped' xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="humayun-thom-arno.jpg" width="500" height="350"></image>
        </svg>
    </div>
    </form>
</body>
</html>
`

**Comment by DominicTobias** [comment] 2016-05-03 09:28
Are you wrapping the cropping inside of the `image` component? It's hard to know what's going wrong because the current version (and a few before) work with Firefox (just tested on v46 on Mac), I think it's pretty unlikely that it wouldn't work on the windows version of FF. As for Edge I can't say as I don't have a Windows machine - if you clone this repo and open `demo/index.html` in Edge (no need to run a server) and select an image does it work? Also please try the same thing but with Firefox (I assume you're on Windows?)

<img width="851" alt="screen shot 2016-05-03 at 10 24 54" src="https://cloud.githubusercontent.com/assets/760314/14979354/b2f3f948-1119-11e6-9e75-7b4f26098bda.png">

**Comment by projecteon** [comment] 2016-05-10 06:02
Ok, I got the demo to work in FF but not in IE.

I think the issue I had with FF was my refactoring to use canvas as a base for image viewing instead of image, and I guess FF does not support polygon over canvas but do to img tags. Shame :/

**Comment by DominicTobias** [comment] 2016-05-12 09:44
H yeah I don't think there's a solution other than using 4 moving boxes, I'll think about it implementing it

**Comment by DominicTobias** [comment] 2016-05-13 15:08
I have tried the alternative of 4 moving boxes (see above PR) and I would have been happy to implement it. But the problem is that unlike most cropping tools this one is based off percentages - this has some advantages like being responsive but it also means that when setting percentages on the 4 boxes there can sometimes be a 1pixel miscalculation meaning the a box overlaps or underlaps by 1px. This results in flickering lines as you drag around. It might be possible to round up the percentages so that things fit nicely though.

**Comment by DominicTobias** [comment] 2016-05-30 10:57
Closing this as it seems like 4 moving boxes isn't going to work with percentages, I hope IE Edge will get clip path support in the near future. I've added a browser compatibility section to the readme. Sorry about that!

**Closed by DominicTobias** 2016-05-30 10:57 UTC

**Comment by projecteon** [comment] 2016-06-07 07:04
I actually had the clip boxes working ok, but the shadow layover is what was not working.
![your_gif_from_mp4togif_com_1465283041442](https://cloud.githubusercontent.com/assets/2820276/15848704/d6dd3e7e-2c8e-11e6-8e94-a2715295ec86.gif)
