### ISSUE TITLE
Aspect ratio in Chrome throws console errors

### ISSUE THREAD

**Issue by CanadaJ** [DominicTobias/react-image-crop#37] opened 2016-06-03 00:49 UTC
I'm using the latest (1.0.0-rc3) version of react-image-crop with the following crop attributes:

```
const cropAttributes = {
  width: 100,
  height: 12,
  x: 0,
  y: 0,
  aspect: 1663/200
}
```

and I'm receiving the following error in the Chrome console:
`Error: <polygon> attribute points: Expected number, "0 0, 1 0, 1 NaN, 0 NaN".`

Interestingly enough, this error has no effect on the crop. Everything works as expected, the aspect ratio is locked, the height, width, and coordinates are also correct, even with different values.

It seems that the inclusion of `aspect` in the attributes is the only thing that causes this error. Also, if the `aspect` is the only attribute specified, no error occurs:

```
const cropAttributes = {
  aspect: 1663/200
}
```

I suspect this might be an issue with webkit but I'm not 100% certain.

**Comment by DominicTobias** [comment] 2016-06-03 07:56
Hi, that's strange I'm not getting the same error with those params on OSX Chrome 50.0.2661.102 (64-bit) or 51.0.2704.79 (64-bit). What Chrome version are you using?

**Comment by DominicTobias** [comment] 2016-06-17 13:11
Closing but feel free to update

**Comment by scriptype** [comment] 2016-08-17 12:25
@CanadaJ I was having this issue. I later found that I was accidentally passing `"1:1"` for the aspect, instead of `1/1`. I suggest checking everything twice.

**Comment by ouchxp** [comment] 2016-10-11 22:20
I was having this issue then found that I was passing string `"1/1"` not the number `1/1` which is `1`

**Comment by fwchen** [comment] 2017-01-27 08:38
Same issue. Has it been fixed?

**Comment by DominicTobias** [comment] 2017-01-27 09:35
I've changed the code for this but since it's a breaking change I'm going to v2 and making one or two other breaking changes too (such as removing the ellipses option). This weekend I'll also be trying to make an alternative to the "marching ants" (the moving dotted lines) before releasing this as using css linear gradients is eating a ridiculous amount of CPU

**Closed** 2017-01-29 22:22 UTC

**Comment by isaachinman** [comment] 2017-02-24 10:03
I still get this error, with the following setup:

    <ReactCrop
      crop={{ aspect: 1, width: 100, top: 0, x: 20 }}
      src={photo}
    />

This is in `v2.0.2`.

**Comment by DominicTobias** [comment] 2017-02-24 18:14
Hm strange, I'll check it over the weekend - when you inspect do you see a
crossorigin attribute?

**Comment by isaachinman** [comment] 2017-02-24 18:26
Sorry, inspect what? The actual DOM?

**Comment by DominicTobias** [comment] 2017-02-25 00:03
Yep!

**Comment by isaachinman** [comment] 2017-02-25 11:21
In that case I'm not really sure what you're asking, but no - there is no immediately obvious DOM node with a `crossorigin` attribute.

**Comment by DominicTobias** [comment] 2017-02-25 11:31
Hey sorry, I probably shouldn't answer stuff when I'm drunk I'm a bar 😃 I
thought this was regarding a different issue. Are you getting the same
error as the OP? What does it say and what are you passing in as props?

**Comment by isaachinman** [comment] 2017-02-25 11:36
**The error:**

`DOMPropertyOperations.js?17f3:142 Error: <polygon> attribute points: Expected number, "0.2 0, 1 0, 1 NaN, 0.2 NaN".`

**The config:**

    <ReactCrop
      crop={{ aspect: 1, width: 100, top: 0, x: 20 }}
      src={photo.preview}
      onComplete={this.setCroppingData}
      onImageLoaded={(crop, image, pixelCrop) => this.setCroppingData(crop, pixelCrop)}
    />

**Comment by DominicTobias** [comment] 2017-02-25 15:15
Hm I can't replicate using that crop prop. In `getPolygonValues(forSvg) {` function put `console.log(crop.x, crop.y, crop.height)`, I have a feeling your crop.height could be not a number

**Comment by isaachinman** [comment] 2017-02-25 15:19
Yes, that's it exactly. Seems that function is called a few times, one of which `crop.height` was `NaN`. What can I do to prevent this?

**Comment by DominicTobias** [comment] 2017-02-25 15:22
I am guessing that at some point something unusual is being pass into the cropper, try in your render method logging out the crop props you are passing in, maybe one of them is not a number, or a number as a string or something. If not I'll have to try and get a reproducible example to debug.

**Comment by isaachinman** [comment] 2017-02-25 16:07
As per my initial post:

`<ReactCrop crop={{ aspect: 1, width: 100, top: 0, x: 20 }} src={newProfilePhoto.preview} />`

That is what I am passing in. They are all integers. No strings, no `NaN`, nothing except valid integers.

I am never even sending height, so however it is being assigned `NaN` is happening within `react-image-crop`.

**Comment by DominicTobias** [comment] 2017-02-25 16:09
Ok can you upload the image somewhere and post a link? I want to see if I
can replicate it if I use the exact props. Also what browser/version are
you using?

**Comment by isaachinman** [comment] 2017-02-25 16:13
**Browser:** Chrome, Version 56.0.2924.87 (64-bit) [OSX]

**react-image-crop:** v2.0.2

**Image:** https://i.imgur.com/diacaXd.png

**Comment by isaachinman** [comment] 2017-02-25 16:14
The only thing I can think is that it's related to the fact that the `x` value in combination with the `aspect` value forces a recalculation of the `width` value (I assume this is happening somewhere in your code).

**Comment by DominicTobias** [comment] 2017-02-27 08:39
I can't replicate your issue by using that crop and choosing that image (using react-image-crop/demo/index.html). It's likely something else you're doing but I can't solve it unless you can provide a working example of the error sorry

**Comment by isaachinman** [comment] 2017-02-27 09:19
That _is_ a working example, I assure you. I can reproduce with just that data in a clean environment. At any rate, like I have said it doesn't seem to inhibit functionality so it's not a priority for me.
