### ISSUE TITLE
crop box resets offset when hits the bottom

### ISSUE THREAD

**Issue by matteogabella** [DominicTobias/react-image-crop#324] opened 2019-11-28 10:32 UTC
hi, i have this weird behaviour... not in all images, but with some particular images when i hit the image bottom boundary, the crop box goes back the top...
any suggestion?
thank you!
Matteo

![ezgif com-crop](https://user-images.githubusercontent.com/5822102/69798784-3fd5c500-11d2-11ea-8f3e-2ecf7f2e9e3c.gif)

**Comment by DominicTobias** [comment] 2019-11-28 15:10
Hi are you able to reproduce this on the sandbox demo? https://codesandbox.io/s/72py4jlll6

**Comment by thiskevinwang** [comment] 2019-12-30 08:07
I noticed this too. I found steps to reproduce:

In playground:
- upload image
- inspect element
- find the `<img class="ReactCrop__image" ...`
- manually apply, via browser devtools
  ```css
  margin-bottom: 40px;
  ```
- drag the cropper to the bottom 💥

**Comment by DominicTobias** [comment] 2019-12-30 16:07
Thanks will look into this soon

**Comment by DominicTobias** [comment] 2019-12-31 19:23
Is this bug specifically about setting a margin-bottom on ReactCrop__image? That's the only way I have replicated it, but that is not intended to be played with. I would question why you are adding a margin there?

**Comment by thiskevinwang** [comment] 2019-12-31 22:55
I noticed it with an "image container" element creating a black space below the image.
- Saw this issue
- Didn't remember how to reproduce my experience
- I tried to reproduce it in the codesandbox in the quickest way possible

**Comment by DominicTobias** [comment] 2020-01-05 12:10
Thanks, only problem is that I can't replicate without the margin and the bug is specifically because of the margin, though there might be some other scenario where it could break I'm not sure 🤔

**Comment by DominicTobias** [comment] 2020-01-05 12:16
However I know how I can fix that issue, and in doing so it might fix the other

**Comment by DominicTobias** [comment] 2020-01-05 13:58
I've fixed the issue caused by margin at least in 8.4.3. Possibly fixes the original issue but can't be sure as I'm not sure how to replicate it. If you think it's fixed let me know!

**Comment by musama96** [comment] 2020-01-13 13:17
For me it comes on mobile if I take a portrait image, the image gets rotated. I was using the given code to reset the orientation of the image but when I move the cropper to the bottom, it jumps to the top automatically.

`import piexif from "piexifjs";

export default function(srcBase64, callback) {
   if (!srcBase64.startsWith('data:image/jpeg')) {
      return callback(srcBase64);
   }
   
   const exif = piexif.load(srcBase64);
   const exif0 = exif['0th'];
   
   if (!exif0 || !exif0[piexif.ImageIFD.Orientation]) {
      return callback(srcBase64);
   }
   
   const srcOrientation = exif0[piexif.ImageIFD.Orientation];
   
   if (srcOrientation < 2 || srcOrientation > 8) {
      return callback(srcBase64);
   }
   
   const img = new Image();
   
   img.onload = () => {
      const width = img.width,
         height = img.height,
         canvas = document.createElement('canvas'),
         ctx = canvas.getContext('2d');
      
      if (4 < srcOrientation && srcOrientation < 9) {
         canvas.width = height;
         canvas.height = width;
      }
      else {
         canvas.width = width;
         canvas.height = height;
      }
      
      switch (srcOrientation) {
         case 2: ctx.transform(-1, 0, 0, 1, width, 0); break;
         case 3: ctx.transform(-1, 0, 0, -1, width, height); break;
         case 4: ctx.transform(1, 0, 0, -1, 0, height); break;
         case 5: ctx.transform(0, 1, 1, 0, 0, 0); break;
         case 6: ctx.transform(0, 1, -1, 0, height, 0); break;
         case 7: ctx.transform(0, -1, -1, 0, height, width); break;
         case 8: ctx.transform(0, -1, 1, 0, 0, width); break;
         default: break;
      }
      
      ctx.drawImage(img, 0, 0);
      
      callback(canvas.toDataURL());
   };
   
   img.src = srcBase64;
}
`

**Comment by DominicTobias** [comment] 2020-01-13 13:24
@musama96 what version are you using? Did you override any styling in the cropper?

P.S. you can make that code not block the main thread if you make the function async and use `toBlob` instead of `toDataURL`, which is also a lot faster to run.

**Comment by musama96** [comment] 2020-01-13 13:27
the version is 8.5.0
no I didn't override any styling.

**Comment by DominicTobias** [comment] 2020-01-13 14:19
@musama96 And doing the same crop and image works on desktop? Can you let me know the crop settings you are using (aspect and width and height if set and `px` or `%`) and also the image dimensions pls?

**Comment by musama96** [comment] 2020-01-13 14:29
yes it works fine on desktop. Aspect : 1 , width : 30 and unit %. Image resolution : 4032 * 3024

**Comment by DominicTobias** [comment] 2020-01-17 13:13
Hm thanks, I tried to replicate the issue on Chrome inspector with touch emulation and also iOS Safari and iOS Chrome and didn't manage to 🤔

**Comment by musama96** [comment] 2020-01-17 14:26
Issue occurs when the height of image element is less than height of image wrapper. Issue has been replicated in this demo : https://codesandbox.io/s/react-image-crop-demo-771t0

**Comment by DominicTobias** [comment] 2020-01-17 17:07
You said you didn't override styling but the issue only happens if you do. Any thanks I can replicate it with that demo but that's also the reason I asked what version you are using and you said 8.5.0. I fixed the only way I can replicate that issue in 8.5.0, the demo you sent is running 8.4.0. If you click this refresh icon to upgrade to 8.5.0 it stops happening:

![Screenshot 2020-01-18 at 01 06 55](https://user-images.githubusercontent.com/760314/72631179-de8ad080-398e-11ea-85c5-5e9d020daab4.png)

**Comment by DominicTobias** [comment] 2020-01-25 08:39
Closing this, let me know if the problem still occurs but should be fixed as per previous comment

**Comment by pvanosch** [comment] 2020-02-25 07:38
Hi, I'm experiencing the same problem on chrome mobile android (works fine on chrome desktop) with version 8.5.0 using this style:

`.ReactCrop__image {
  max-width: 100%;
  max-height: 420px;
  object-fit: contain;
  background-color: $color-white;
}`

It happens with any image, no aspect, using %, width & height 50. Am I doing something wrong here?

**Comment by samuelpetroline** [comment] 2020-03-13 18:46
The error still happens but only on some very specific cases. In my case it happens when I use **percentage crop**. The error happens on this line:

https://github.com/DominicTobias/react-image-crop/blob/16255171d4789fa50893812bfe4ef697ae0fda57/lib/ReactCrop.js#L152

In my case it was doing this comparison:

`pixelCrop.x + pixelCrop.width > imageWidth => 589.0000000000001 + 273 > 862`

Which returned true and caused the crop box to reset. Not sure the best way to fix this. Any ideas @DominicTobias ?

**Comment by samuelpetroline** [comment] 2020-03-13 18:51
Also, it happens only at some specifics crop box sizes, i.e when it's 273x273.06 but not when it's 275x275.06.

**Comment by DominicTobias** [comment] 2020-03-14 07:15
@samuelpetroline or @pvanosch if you are able to reproduce this on the demo https://codesandbox.io/s/72py4jlll6 (i.e. set the crop object to when it happens with an image of width/height that would be of great help

**Comment by pvanosch** [comment] 2020-03-23 20:39
@DominicTobias I've reproduced the issue here: https://codesandbox.io/s/react-image-crop-demo-s8xr4 With image 4032(w) 3024(h) px. It happens when I move the crop to the right on Android Chrome and Samsung internet (haven't tested it on other mobile browsers).

**Comment by DominicTobias** [comment] 2020-03-30 08:36
Still having trouble replicating but found a potential cause, please give 8.6.0 a try

**Comment by DominicTobias** [comment] 2020-04-08 14:39
Closing again, please ensure you use the latest 8.6.2. If the problem occurs again I will re-open

**Closed by DominicTobias** 2020-04-08 14:39 UTC
